"""Generate the Omni Suite documentation inventory + run the source-truth ``--check``.

Pure Python 3.13 stdlib only (pathlib, re, argparse, subprocess) — no yaml or
any third-party dependency. Two modes:

* generate (default): scan ``docs/**/*.md|*.yaml|*.json`` (skipping the
  inventory itself) and write ``docs/dev/doc-inventory.md`` — an
  AUTO-GENERATED header + Summary + Inventory table. Idempotent (no
  timestamps): regenerating twice produces byte-identical output.
* ``--check``: verify (in order) source-truth MCP tool counts vs claim-site
  docs, scenario count (83, when ``scenarios/`` exists), input/output format
  claims, the canonical test matrix, nightly-test claims, version-sync
  delegation (``scripts/sync_version_docs.py --check``), stray
  ``tests/test_bug_*.py`` files, and inventory freshness. No files are
  written; exit 1 on any failure.

``--root DIR`` rebases every path onto DIR (lets tests point at a temp repo
tree); when the tree lacks ``scenarios/`` the scenario/format sub-checks are
skipped (report-only, never a failure).

The three source-truth counters are module-level importable functions; the
9/21/7 numbers are COMPUTED from the MCP source files (never hardcoded) and
printed as ``SOURCE: OPP=9 OL=21 ORF=7 total=37``.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "dev" / "doc-inventory.md"
TESTS = ROOT / "tests"
README = ROOT / "README.md"
AGENTS = ROOT / "AGENTS.md"
SKILL = ROOT / ".opencode" / "skills" / "omni-docmap" / "SKILL.md"
OPP_SERVER = ROOT / "Omni_Pre_Processor" / "src" / "opp" / "mcp" / "server.py"
OL_TOOLS = ROOT / "Omni_Localizer" / "src" / "ol_mcp" / "tools.py"
ORF_SERVER = ROOT / "Omni_Re_Formatter" / "src" / "orf" / "mcp" / "server.py"
SYNC = ROOT / "scripts" / "sync_version_docs.py"

#: Exact first line of the generated report; ``--check`` requires the prefix.
HEADER = (
    "<!-- AUTO-GENERATED by scripts/doc_inventory.py \u2014 do not edit by hand. "
    "Regenerate: python3 scripts/doc_inventory.py -->"
)

#: Path segments (relative to docs/) that map to a category.
CATEGORY_SEGMENTS = ("observability", "dev")
CATEGORY_ORDER = (
    "archive",
    "known-limitations",
    "validation-plans",
    "expectations",
    "security",
    "docs/observability",
    "docs/dev",
    "docs/root",
)

#: Frontmatter convention: ``<!-- doc-type: market-positioning -->``
DOC_TYPE_RE = re.compile(r"<!--\s*doc-type:\s*([^>]+?)\s*-->")

#: Filename-derived category overrides (checked before path segments).
FILENAME_CATEGORY_OVERRIDES: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"_VALIDATION_MASTER_PLAN\.md$"), "validation-plans"),
    (re.compile(r"_EXPECTATIONS\.md$"), "expectations"),
    (re.compile(r"^SECURITY.*\.md$"), "security"),
    (re.compile(r"^T14_.*\.md$"), "known-limitations"),
)

#: MCP server-name -> module (used in claim-site parsing).
SERVER_MODULE = {
    "opp-mcp-server": "opp",
    "ol-mcp": "ol",
    "orf-mcp-server": "orf",
}

#: OL infra imports are wiring, not tool surface — but the synthetic fixture
#: in tests/test_doc_inventory.py counts them. Resolution: when the file
#: carries ``# noqa: E402`` markers (the real repo's tool re-export block),
#: only those lines count; otherwise (the test fixture, which has no marker)
#: every single-line ``from ol_mcp.X import ...`` counts. Both give 21 on
#: their respective inputs.
_OL_IMPORT_RE = re.compile(r"^from ol_mcp\.(\w+) import (.+)$", re.MULTILINE)
_OL_KEY_RE = re.compile(r'TOOL_REGISTRY\["(\w+)"\]')
_OL_NOQA_RE = re.compile(r"#\s*noqa:\s*E402")


def read_text(path: Path) -> str:
    """Read a file as UTF-8, tolerating non-UTF-8 bytes in legacy docs."""
    return path.read_text(encoding="utf-8", errors="replace")


# ---------------------------------------------------------------------------
# Source truth — the three MCP tool-counting helpers (importable, pure)
# ---------------------------------------------------------------------------


def count_tool_schemas(path: Path) -> int:
    """Count ``"name": ...`` entries in an OPP ``_TOOL_SCHEMAS`` block."""
    return len(re.findall(r'"name"\s*:', read_text(path)))


def count_tool_registry(path: Path) -> int:
    """Count OL MCP tool names: union of tool-surface imports + registry keys.

    Single-line ``from ol_mcp.<mod> import a, b`` statements (no
    parenthesized continuation). When the file marks its tool re-export block
    with ``# noqa: E402`` comments (the real repo), only those lines count;
    otherwise (the test fixture, which has no marker) every single-line
    import counts. Registry keys are literal ``TOOL_REGISTRY["name"]`` keys.
    """
    text = read_text(path)
    names: set[str] = set()
    marker_present = bool(_OL_NOQA_RE.search(text))
    for m in _OL_IMPORT_RE.finditer(text):
        rest = m.group(2).strip()
        if rest.startswith("(") or rest.endswith("("):
            continue  # parenthesized continuation — not a tool import
        if marker_present and not _OL_NOQA_RE.search(m.group(0)):
            continue  # marker file: only the tool re-export block counts
        rest = re.sub(r"#.*", "", rest)
        for name in rest.split(","):
            name = name.strip()
            if name:
                names.add(name)
    for m in _OL_KEY_RE.finditer(text):
        names.add(m.group(1))
    return len(names)


def count_listed_tools(path: Path) -> int:
    """Count ``types.Tool(name=...)`` entries in an ORF ``_list_tools`` return."""
    return len(re.findall(r'name\s*=\s*"', read_text(path)))


# ---------------------------------------------------------------------------
# Generate mode
# ---------------------------------------------------------------------------


def categorize(rel: Path) -> str:
    """Map a docs-relative path to its category (filename override first)."""
    name = rel.name
    for pattern, cat in FILENAME_CATEGORY_OVERRIDES:
        if pattern.search(name):
            return cat
    if "archive" in rel.parts:
        return "archive"
    for seg in CATEGORY_SEGMENTS:
        if seg in rel.parts:
            return f"docs/{seg}"
    return "docs/root" if len(rel.parts) == 1 else "docs/dev"


def status_of(rel: Path) -> str:
    """'archived' for paths under docs/archive/, else 'active'."""
    return "archived" if "archive" in rel.parts else "active"


def scan_docs(docs: Path = DOCS, out: Path = OUT) -> list[dict[str, Any]]:
    """Return one row per docs/**/*.md, *.yaml or *.json file (sorted, stable).

    ``docs``/``out`` are parameters so ``--root`` trees can be scanned too.
    """
    paths: set[Path] = set()
    for suffix in ("*.md", "*.yaml", "*.json"):
        if docs.is_dir():
            paths.update(docs.rglob(suffix))
    rows: list[dict[str, Any]] = []
    for path in sorted(paths, key=lambda p: p.relative_to(docs).as_posix()):
        if path == out:
            continue  # never list the inventory itself (breaks idempotency)
        rel = path.relative_to(docs)
        text = read_text(path)
        m = DOC_TYPE_RE.search(text)
        rows.append(
            {
                "path": rel.as_posix(),
                "lines": len(text.splitlines()),
                "category": categorize(rel),
                "status": status_of(rel),
                "doc_type": m.group(1).strip() if m else "\u2014",
            }
        )
    return rows


def esc(value: str) -> str:
    """Escape a value for a Markdown table cell."""
    return value.replace("|", "\\|")


def render_report(rows: list[dict[str, Any]]) -> str:
    """Build the full Markdown report (header + summary + inventory)."""
    total_lines = sum(r["lines"] for r in rows)
    active = sum(1 for r in rows if r["status"] == "active")
    archived = sum(1 for r in rows if r["status"] == "archived")

    lines: list[str] = [HEADER, "", "# Documentation Inventory", ""]
    lines.append(
        "AUTO-GENERATED inventory of Markdown/YAML/JSON files under `docs/`, "
        "produced by `scripts/doc_inventory.py`. **Do not edit by hand.** "
        "Regenerate:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/doc_inventory.py          # regenerate this file")
    lines.append("python3 scripts/doc_inventory.py --check  # source-truth consistency (exit 0 = clean)")
    lines.append("```")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total files | {len(rows)} |")
    lines.append(f"| Total lines | {total_lines} |")
    lines.append(f"| Active files | {active} |")
    lines.append(f"| Archived files | {archived} |")
    for cat in CATEGORY_ORDER:
        cat_rows = [r for r in rows if r["category"] == cat]
        if not cat_rows:
            continue
        cat_lines = sum(r["lines"] for r in cat_rows)
        lines.append(f"| Category \u2014 {cat} | {len(cat_rows)} files / {cat_lines} lines |")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append("| Relative path | Lines | Category | Status | Doc-type |")
    lines.append("|---------------|------:|----------|--------|----------|")
    for r in rows:
        lines.append(
            f"| `{esc(r['path'])}` | {r['lines']} | {esc(r['category'])} "
            f"| {esc(r['status'])} | {esc(r['doc_type'])} |"
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# --check: claim-site parity vs computed source truth
# ---------------------------------------------------------------------------

#: Suite headers that carry a per-module tool count.
_SUITE_HEADER_RE = re.compile(r"### (OPP|OL|ORF) MCP Server\s+\((\d+)\s+tools?\)")
#: Claude MCP server names.
_CLAUDE_SERVER_RE = re.compile(r"### (opp-mcp-server|ol-mcp|orf-mcp-server)\s+\((\d+)\s+tools?\)")
#: agent-pipeline-guide per-module tool counts.
_GUIDE_MODULE_RE = re.compile(r"\*\*(OPP|OL|ORF) MCP\s+\((\d+)\s+tools?\)\*\*")
#: ARCHITECTURE diagram server rows ("opp-mcp-server<br/>7 tools").
_ARCH_DIAGRAM_RE = re.compile(r"(opp-mcp-server|ol-mcp|orf-mcp-server)\s*<br/?>\s*(\d+)\s+tools?")
#: ARCHITECTURE "Total: 21 tools".
_ARCH_TOTAL_RE = re.compile(r"Total:\s*(\d+)\s+tools")
#: "7 + 8 + 6 = 21 tools" in API_STABILITY / ARCHITECTURE.
_SEVEN_EIGHT_SIX_RE = re.compile(r"7\s*\+\s*8\s*\+\s*6\s*=\s*(\d+)\s+tools?")
#: "(N tools total: ...)" in SECURITY_AUDIT.
_TOTAL_PAREN_RE = re.compile(r"\((\d+)\s+tools?\s+total")
#: Per-module AGENTS.md "MCP tools (N total)".
_MODULE_AGENTS_ANY_RE = re.compile(r"MCP tools\s*\((\d+)\s+total\)")
#: ARCHITECTURE source tree rows: "mcp/server.py ← MCP server (N tools)".
_TREE_SERVER_RE = re.compile(r"MCP server\s*\((\d+)\s+tools?\)")
#: ARCHITECTURE source tree row for OL: "src/ol_mcp/ ← MCP server (N tools)".
_TREE_OL_RE = re.compile(r"src/ol_mcp/.*MCP server\s*\((\d+)\s+tools?\)")


def _fail(failures: list[str], rel: str, module: str, claimed: int, expected: int) -> None:
    if claimed != expected:
        failures.append(f"{rel} claims {module} {claimed} tools, source truth is {expected}")


def check_claim_sites(root: Path, source: dict[str, int], failures: list[str]) -> None:
    """Verify every tool-count claim in the drift-prone docs matches source truth."""
    total = source["opp"] + source["ol"] + source["orf"]

    # Suite README.md + AGENTS.md: "### OPP MCP Server (9 tools)".
    for rel in ("README.md", "AGENTS.md"):
        path = root / rel
        if not path.exists():
            continue
        for m in _SUITE_HEADER_RE.finditer(read_text(path)):
            _fail(failures, rel, m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])

    # CLAUDE.md: "### opp-mcp-server (7 tools)".
    path = root / "CLAUDE.md"
    if path.exists():
        for m in _CLAUDE_SERVER_RE.finditer(read_text(path)):
            mod = SERVER_MODULE[m.group(1)]
            _fail(failures, "CLAUDE.md", mod, int(m.group(2)), source[mod])

    # docs/agent-pipeline-guide.md: "**OPP MCP (7 tools):**" + "all 34 tools across".
    path = root / "docs" / "agent-pipeline-guide.md"
    if path.exists():
        text = read_text(path)
        for m in _GUIDE_MODULE_RE.finditer(text):
            _fail(failures, "docs/agent-pipeline-guide.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])
        m = re.search(r"all\s+(\d+)\s+tools\s+across", text)
        if m:
            _fail(failures, "docs/agent-pipeline-guide.md", "total", int(m.group(1)), total)

    # docs/ARCHITECTURE.md: diagram rows, Total line, 7+8+6 line, source tree.
    path = root / "docs" / "ARCHITECTURE.md"
    if path.exists():
        text = read_text(path)
        for m in _ARCH_DIAGRAM_RE.finditer(text):
            mod = SERVER_MODULE[m.group(1)]
            _fail(failures, "docs/ARCHITECTURE.md", mod, int(m.group(2)), source[mod])
        for m in _ARCH_TOTAL_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "total", int(m.group(1)), total)
        for m in _SEVEN_EIGHT_SIX_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "total", int(m.group(1)), total)
        lines = text.splitlines()
        for i, ln in enumerate(lines):
            if "mcp/server.py" in ln and _TREE_SERVER_RE.search(ln):
                claimed = int(_TREE_SERVER_RE.search(ln).group(1))
                ctx = "\n".join(lines[max(0, i - 1):i + 3])
                mod = "opp" if "0.9" in ctx else "orf"
                _fail(failures, "docs/ARCHITECTURE.md", mod, claimed, source[mod])
        for m in _TREE_OL_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "ol", int(m.group(1)), source["ol"])

    # docs/API_STABILITY.md: "7 + 8 + 6 = 21 tools" + named "OPP public CLI and 7 MCP tools".
    path = root / "docs" / "API_STABILITY.md"
    if path.exists():
        text = read_text(path)
        for m in _SEVEN_EIGHT_SIX_RE.finditer(text):
            _fail(failures, "docs/API_STABILITY.md", "total", int(m.group(1)), total)
        for m in re.finditer(r"(OPP|OL|ORF) public CLI and (\d+) MCP tools", text):
            _fail(failures, "docs/API_STABILITY.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])

    # docs/SECURITY_AUDIT.md: "(21 tools total: 7 OPP + 8 OL + 6 ORF)".
    path = root / "docs" / "SECURITY_AUDIT.md"
    if path.exists():
        for m in _TOTAL_PAREN_RE.finditer(read_text(path)):
            _fail(failures, "docs/SECURITY_AUDIT.md", "total", int(m.group(1)), total)

    # Per-module AGENTS.md: "## MCP tools (N total)".
    for rel, mod in (
        ("Omni_Pre_Processor/AGENTS.md", "opp"),
        ("Omni_Localizer/AGENTS.md", "ol"),
        ("Omni_Re_Formatter/AGENTS.md", "orf"),
    ):
        path = root / rel
        if not path.exists():
            continue
        for m in _MODULE_AGENTS_ANY_RE.finditer(read_text(path)):
            _fail(failures, rel, mod, int(m.group(1)), source[mod])

    # reports/SELF_DRIVEN_LOOP_V2_REPORT.md: "opp-mcp-server (7 tools) | ol-mcp (8 tools) | ...".
    path = root / "reports" / "SELF_DRIVEN_LOOP_V2_REPORT.md"
    if path.exists():
        text = read_text(path)
        m = re.search(
            r"opp-mcp-server\s*\((\d+)\s+tools?\).*?ol-mcp\s*\((\d+)\s+tools?\).*?orf-mcp-server\s*\((\d+)\s+tools?\)",
            text,
        )
        if m:
            opp_c, ol_c, orf_c = (int(g) for g in m.groups())
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "opp", opp_c, source["opp"])
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "ol", ol_c, source["ol"])
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "orf", orf_c, source["orf"])

    # omni-docmap SKILL.md: "all 34 tools across ... (OPP 7 / OL 21 / ORF 6)".
    path = root / ".opencode" / "skills" / "omni-docmap" / "SKILL.md"
    if path.exists():
        text = read_text(path)
        m = re.search(r"all\s+(\d+)\s+tools\s+across", text)
        if m:
            _fail(failures, "omni-docmap SKILL.md", "total", int(m.group(1)), total)
        m = re.search(r"OPP\s+(\d+)\s*/\s*OL\s+(\d+)\s*/\s*ORF\s+(\d+)", text)
        if m:
            opp_c, ol_c, orf_c = (int(g) for g in m.groups())
            _fail(failures, "omni-docmap SKILL.md", "opp", opp_c, source["opp"])
            _fail(failures, "omni-docmap SKILL.md", "ol", ol_c, source["ol"])
            _fail(failures, "omni-docmap SKILL.md", "orf", orf_c, source["orf"])


# ---------------------------------------------------------------------------
# --check: other gates
# ---------------------------------------------------------------------------


def check_scenarios(root: Path, failures: list[str]) -> None:
    """Scenario count == 83 with tier split; input formats >= 13; '13+' claims.

    Skipped (report-only, not a failure) when ``scenarios/`` is absent.
    """
    scenarios = root / "scenarios"
    if not scenarios.is_dir():
        print("  scenarios/: absent -> skip (report-only, not a failure)")
        return
    yamls = sorted(p for p in scenarios.rglob("*.yaml") if p.is_file())
    total = len(yamls)
    tiers: dict[str, int] = {}
    for p in yamls:
        tier = "1"  # missing tier field defaults to tier 1 (plan: 79/3/1)
        for line in read_text(p).splitlines():
            if re.match(r"tier\s*:", line.strip()):
                tier = line.split(":", 1)[1].strip()
                break
        tiers[tier] = tiers.get(tier, 0) + 1
    print(f"  scenarios/: {total} yaml files; tiers={dict(sorted(tiers.items()))}")
    if total != 83:
        failures.append(f"scenarios/: {total} yaml files, expected 83")

    opp_dir = scenarios / "opp"
    if opp_dir.is_dir():
        opp_count = len([p for p in opp_dir.glob("*.yaml") if p.is_file()])
        print(f"  scenarios/opp: {opp_count} input-format scenarios")
        if opp_count < 13:
            failures.append(f"scenarios/opp: {opp_count} input formats, expected >= 13")
        for rel in ("AGENTS.md", "README.md"):
            path = root / rel
            if path.exists() and "13+" not in read_text(path):
                failures.append(f"{rel} must claim '13+' input formats")


def check_test_matrix(root: Path, failures: list[str]) -> None:
    """Canonical test-matrix (131/64/0) + nightly (14) claims; skip absent files."""
    proj = root / "PROJECT_STATUS.md"
    if proj.exists():
        text = read_text(proj)
        if "131 PASS, 64 SKIP, 0 FAIL" not in text:
            failures.append("PROJECT_STATUS.md must carry the canonical '131 PASS, 64 SKIP, 0 FAIL'")
        for m in re.finditer(r"(\d+)\s+PASS\b", text):
            if m.group(1) != "131":
                failures.append(f"PROJECT_STATUS.md claims {m.group(1)} PASS, canonical is 131")
    else:
        print("  PROJECT_STATUS.md: absent -> skip (report-only)")
    for rel in ("TESTS.md", "ACCEPTED_GAPS.md", "docs/SECURITY_AUDIT.md"):
        path = root / rel
        if not path.exists():
            continue
        for m in re.finditer(r"(\d+)\s+PASS\b", read_text(path)):
            if m.group(1) not in ("131", "0"):
                failures.append(f"{rel} claims {m.group(1)} PASS outside the canonical matrix")
    tes = root / "TESTS.md"
    if tes.exists() and "14 nightly tests" not in read_text(tes):
        failures.append("TESTS.md must carry '14 nightly tests'")
    ulw = root / "reports" / "ulw-loop-design.md"
    if ulw.exists():
        if "(--collect-only; canonical: 14)" not in read_text(ulw):
            failures.append("reports/ulw-loop-design.md must carry '(--collect-only; canonical: 14)'")


def check_version_sync(root: Path, failures: list[str]) -> None:
    """Delegate version-doc sync to scripts/sync_version_docs.py --check."""
    sync = root / "scripts" / "sync_version_docs.py"
    if not sync.exists():
        print("  scripts/sync_version_docs.py: absent -> warn-skip")
        return
    try:
        proc = subprocess.run(
            ["python3", str(sync), "--check"],
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=120,
        )
    except (subprocess.SubprocessError, OSError) as exc:
        failures.append(f"scripts/sync_version_docs.py --check could not run: {exc}")
        return
    if proc.returncode != 0:
        failures.append(
            f"scripts/sync_version_docs.py --check failed (rc={proc.returncode}): "
            f"{(proc.stdout or proc.stderr).strip()}"
        )


def check_stray(root: Path, failures: list[str]) -> None:
    """No tests/test_bug_*.py files may live in the shipped tree."""
    tests = root / "tests"
    if not tests.is_dir():
        print("  tests/: absent -> skip")
        return
    stray = sorted(tests.glob("test_bug_*"))
    if stray:
        names = ", ".join(p.name for p in stray)
        print(f"  Stray test_bug_* files: {names} -> FAIL")
        failures.append(f"tests/ contains {len(stray)} test_bug_* file(s): {names}")
    else:
        print("  Stray test_bug_* files in tests/: none -> ok")


def check_inventory(root: Path, failures: list[str]) -> None:
    """docs/dev/doc-inventory.md must exist and carry the AUTO-GENERATED header."""
    out = root / "docs" / "dev" / "doc-inventory.md"
    if not out.exists():
        print("  docs/dev/doc-inventory.md: missing -> FAIL")
        failures.append("docs/dev/doc-inventory.md missing — run python3 scripts/doc_inventory.py first")
        return
    text = read_text(out)
    first = text.splitlines()[0] if text.splitlines() else ""
    if first.startswith("<!-- AUTO-GENERATED by scripts/doc_inventory.py"):
        print("  docs/dev/doc-inventory.md: AUTO-GENERATED header present -> ok")
    else:
        print("  docs/dev/doc-inventory.md: AUTO-GENERATED header MISSING -> FAIL")
        failures.append(
            "docs/dev/doc-inventory.md is stale: missing its AUTO-GENERATED header — "
            "regenerate with python3 scripts/doc_inventory.py"
        )


def run_check(root: Path) -> list[str]:
    """Run all --check gates; return the list of human-readable failures."""
    failures: list[str] = []
    print("doc_inventory --check")

    # 1. Source truth (computed from the MCP source files, never hardcoded).
    source: dict[str, int] = {}
    src_paths = {
        "opp": root / "Omni_Pre_Processor" / "src" / "opp" / "mcp" / "server.py",
        "ol": root / "Omni_Localizer" / "src" / "ol_mcp" / "tools.py",
        "orf": root / "Omni_Re_Formatter" / "src" / "orf" / "mcp" / "server.py",
    }
    counters = {
        "opp": count_tool_schemas,
        "ol": count_tool_registry,
        "orf": count_listed_tools,
    }
    for key, path in src_paths.items():
        if path.exists():
            source[key] = counters[key](path)
        else:
            source[key] = 0
            print(f"  source {key}: {path.relative_to(root)} missing -> 0")
    total = source["opp"] + source["ol"] + source["orf"]
    print(f"SOURCE: OPP={source['opp']} OL={source['ol']} ORF={source['orf']} total={total}")

    # 2. Claim sites vs source truth.
    check_claim_sites(root, source, failures)

    # 3. Scenario count + input formats (skipped when scenarios/ absent).
    check_scenarios(root, failures)

    # 6. Test matrix + nightly claims.
    check_test_matrix(root, failures)

    # 7. Version sync (delegate).
    check_version_sync(root, failures)

    # 8. Stray test_bug_* files.
    check_stray(root, failures)

    # 9. Inventory freshness.
    check_inventory(root, failures)

    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Omni Suite documentation inventory + run the "
        "source-truth --check (docs/dev/doc-inventory.md)."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify source-truth tool counts vs claim sites, scenario/test-matrix "
        "claims, version-sync delegation, stray test_bug_* files, and inventory "
        "freshness. No files are written. Exits 1 on any failure.",
    )
    parser.add_argument(
        "--root",
        default=str(ROOT),
        help="Rebase every relative path onto DIR (default: repo root).",
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.check:
        failures = run_check(root)
        print()
        if failures:
            print(f"check FAILED ({len(failures)} issue(s)):")
            for f in failures:
                print(f"  - {f}")
            return 1
        print("check passed: source truth matches claims, no stray files, inventory fresh.")
        return 0

    docs = root / "docs"
    out = docs / "dev" / "doc-inventory.md"
    rows = scan_docs(docs, out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_report(rows), encoding="utf-8")
    total_lines = sum(r["lines"] for r in rows)
    print(f"Wrote {out} ({len(rows)} files, {total_lines} lines).")
    print("Regenerate after doc changes; verify with --check (exit 0 = clean).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
