"""Generate the Omni Suite documentation inventory + run the source-truth ``--check``.

Pure Python 3.13 stdlib only (pathlib, re, argparse, subprocess) — no yaml or
any third-party dependency. Two modes:

* generate (default): scan ``docs/**/*.md|*.yaml|*.json`` (skipping the
  inventory itself) and write ``docs/dev/doc-inventory.md`` — an
  AUTO-GENERATED header + Summary + Inventory table. Idempotent (no
  timestamps): regenerating twice produces byte-identical output.
* ``--check``: verify (in order) source-truth MCP tool counts vs claim-site
  docs (suite docs + ``Omni_*/docs/**/*.md`` module docs + module READMEs, with
  the narrow self-declared ``vX.Y.Z (matches pyproject.toml)`` module-doc
  version check), scenario count (DERIVED from the ``scenarios/**/*.yaml`` glob,
  never pinned — claim-site docs stating a count must match it; skipped when
  ``scenarios/`` is absent), input/output format claims, the canonical test
  matrix, nightly-test claims, version-sync delegation
  (``scripts/sync_version_docs.py --check``), stray ``tests/test_bug_*.py``
  files, and inventory freshness. No files are written; exit 1 on any failure.

``--root DIR`` rebases every path onto DIR (lets tests point at a temp repo
tree); when the tree lacks ``scenarios/`` the scenario/format sub-checks are
skipped (report-only, never a failure).

The three source-truth counters are module-level importable functions; the
9/21/7 numbers are COMPUTED from the MCP source files (never hardcoded) and
printed as ``SOURCE: OPP=9 OL=21 ORF=7 total=37``.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "dev" / "doc-inventory.md"
TESTS = ROOT / "tests"
README = ROOT / "README.md"
AGENTS = ROOT / "AGENTS.md"
SKILL = ROOT / ".opencode" / "skills" / "omni-docmap" / "SKILL.md"
OPP_SERVER = ROOT / "Omni_Pre_Processor" / "src" / "opp" / "mcp" / "server.py"
OL_TOOLS = ROOT / "Omni_Localizer" / "src" / "ol_mcp" / "tools.py"
ORF_SERVER = ROOT / "Omni_Re_Formatter" / "src" / "orf" / "mcp" / "server.py"
SYNC = ROOT / "scripts" / "sync_version_docs.py"

#: Exact first line of the generated report; ``--check`` requires the prefix.
HEADER = (
    "<!-- AUTO-GENERATED by scripts/doc_inventory.py \u2014 do not edit by hand. "
    "Regenerate: python3 scripts/doc_inventory.py -->"
)

#: Path segments (relative to docs/) that map to a category.
CATEGORY_SEGMENTS = ("observability", "dev")
CATEGORY_ORDER = (
    "archive",
    "known-limitations",
    "validation-plans",
    "expectations",
    "security",
    "docs/observability",
    "docs/dev",
    "docs/root",
)

#: Frontmatter convention: ``<!-- doc-type: market-positioning -->``
DOC_TYPE_RE = re.compile(r"<!--\s*doc-type:\s*([^>]+?)\s*-->")

#: Filename-derived category overrides (checked before path segments).
FILENAME_CATEGORY_OVERRIDES: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"_VALIDATION_MASTER_PLAN\.md$"), "validation-plans"),
    (re.compile(r"_EXPECTATIONS\.md$"), "expectations"),
    (re.compile(r"^SECURITY.*\.md$"), "security"),
    (re.compile(r"^T14_.*\.md$"), "known-limitations"),
)

#: MCP server-name -> module (used in claim-site parsing).
SERVER_MODULE = {
    "opp-mcp-server": "opp",
    "ol-mcp": "ol",
    "orf-mcp-server": "orf",
}

#: OL infra imports are wiring, not tool surface — but the synthetic fixture
#: in tests/test_doc_inventory.py counts them. Resolution: when the file
#: carries ``# noqa: E402`` markers (the real repo's tool re-export block),
#: only those lines count; otherwise (the test fixture, which has no marker)
#: every single-line ``from ol_mcp.X import ...`` counts. Both give 21 on
#: their respective inputs.
_OL_IMPORT_RE = re.compile(r"^from ol_mcp\.(\w+) import (.+)$", re.MULTILINE)
_OL_KEY_RE = re.compile(r'TOOL_REGISTRY\["(\w+)"\]')
_OL_NOQA_RE = re.compile(r"#\s*noqa:\s*E402")


def read_text(path: Path) -> str:
    """Read a file as UTF-8, tolerating non-UTF-8 bytes in legacy docs."""
    return path.read_text(encoding="utf-8", errors="replace")


# ---------------------------------------------------------------------------
# Source truth — the three MCP tool-counting helpers (importable, pure)
# ---------------------------------------------------------------------------


def count_tool_schemas(path: Path) -> int:
    """Count ``"name": ...`` entries in an OPP ``_TOOL_SCHEMAS`` block."""
    return len(re.findall(r'"name"\s*:', read_text(path)))


def count_tool_registry(path: Path) -> int:
    """Count OL MCP tool names: union of tool-surface imports + registry keys.

    Single-line ``from ol_mcp.<mod> import a, b`` statements (no
    parenthesized continuation). When the file marks its tool re-export block
    with ``# noqa: E402`` comments (the real repo), only those lines count;
    otherwise (the test fixture, which has no marker) every single-line
    import counts. Registry keys are literal ``TOOL_REGISTRY["name"]`` keys.
    """
    text = read_text(path)
    names: set[str] = set()
    marker_present = bool(_OL_NOQA_RE.search(text))
    for m in _OL_IMPORT_RE.finditer(text):
        rest = m.group(2).strip()
        if rest.startswith("(") or rest.endswith("("):
            continue  # parenthesized continuation — not a tool import
        if marker_present and not _OL_NOQA_RE.search(m.group(0)):
            continue  # marker file: only the tool re-export block counts
        rest = re.sub(r"#.*", "", rest)
        for name in rest.split(","):
            name = name.strip()
            if name:
                names.add(name)
    for m in _OL_KEY_RE.finditer(text):
        names.add(m.group(1))
    return len(names)


def count_listed_tools(path: Path) -> int:
    """Count ``types.Tool(name=...)`` entries in an ORF ``_list_tools`` return."""
    return len(re.findall(r'name\s*=\s*"', read_text(path)))


# ---------------------------------------------------------------------------
# Generate mode
# ---------------------------------------------------------------------------


def categorize(rel: Path) -> str:
    """Map a docs-relative path to its category.

    The ``archive`` path segment wins over every filename override so an
    archived ``*_VALIDATION_MASTER_PLAN.md`` categorizes as ``archive``,
    never as ``validation-plans``.
    """
    if "archive" in rel.parts:
        return "archive"
    name = rel.name
    for pattern, cat in FILENAME_CATEGORY_OVERRIDES:
        if pattern.search(name):
            return cat
    for seg in CATEGORY_SEGMENTS:
        if seg in rel.parts:
            return f"docs/{seg}"
    return "docs/root" if len(rel.parts) == 1 else "docs/dev"


def status_of(rel: Path) -> str:
    """'archived' for paths under docs/archive/, else 'active'."""
    return "archived" if "archive" in rel.parts else "active"


def scan_docs(docs: Path = DOCS, out: Path = OUT) -> list[dict[str, Any]]:
    """Return one row per docs/**/*.md, *.yaml or *.json file (sorted, stable).

    ``docs``/``out`` are parameters so ``--root`` trees can be scanned too.
    """
    paths: set[Path] = set()
    for suffix in ("*.md", "*.yaml", "*.json"):
        if docs.is_dir():
            paths.update(docs.rglob(suffix))
    rows: list[dict[str, Any]] = []
    for path in sorted(paths, key=lambda p: p.relative_to(docs).as_posix()):
        if path == out:
            continue  # never list the inventory itself (breaks idempotency)
        rel = path.relative_to(docs)
        text = read_text(path)
        m = DOC_TYPE_RE.search(text)
        rows.append(
            {
                "path": rel.as_posix(),
                "lines": len(text.splitlines()),
                "category": categorize(rel),
                "status": status_of(rel),
                "doc_type": m.group(1).strip() if m else "\u2014",
            }
        )
    return rows


def esc(value: str) -> str:
    """Escape a value for a Markdown table cell."""
    return value.replace("|", "\\|")


def render_report(rows: list[dict[str, Any]]) -> str:
    """Build the full Markdown report (header + summary + inventory)."""
    total_lines = sum(r["lines"] for r in rows)
    active = sum(1 for r in rows if r["status"] == "active")
    archived = sum(1 for r in rows if r["status"] == "archived")

    lines: list[str] = [HEADER, "", "# Documentation Inventory", ""]
    lines.append(
        "AUTO-GENERATED inventory of Markdown/YAML/JSON files under `docs/`, "
        "produced by `scripts/doc_inventory.py`. **Do not edit by hand.** "
        "Regenerate:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/doc_inventory.py          # regenerate this file")
    lines.append("python3 scripts/doc_inventory.py --check  # source-truth consistency (exit 0 = clean)")
    lines.append("```")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total files | {len(rows)} |")
    lines.append(f"| Total lines | {total_lines} |")
    lines.append(f"| Active files | {active} |")
    lines.append(f"| Archived files | {archived} |")
    for cat in CATEGORY_ORDER:
        cat_rows = [r for r in rows if r["category"] == cat]
        if not cat_rows:
            continue
        cat_lines = sum(r["lines"] for r in cat_rows)
        lines.append(f"| Category \u2014 {cat} | {len(cat_rows)} files / {cat_lines} lines |")
    lines.append("")
    lines.append("## Inventory")
    lines.append("")
    lines.append("| Relative path | Lines | Category | Status | Doc-type |")
    lines.append("|---------------|------:|----------|--------|----------|")
    for r in rows:
        lines.append(
            f"| `{esc(r['path'])}` | {r['lines']} | {esc(r['category'])} "
            f"| {esc(r['status'])} | {esc(r['doc_type'])} |"
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# --check: claim-site parity vs computed source truth
# ---------------------------------------------------------------------------

#: Suite headers that carry a per-module tool count.
_SUITE_HEADER_RE = re.compile(r"### (OPP|OL|ORF) MCP Server\s+\((\d+)\s+tools?\)")
#: Claude MCP server names.
_CLAUDE_SERVER_RE = re.compile(r"### (opp-mcp-server|ol-mcp|orf-mcp-server)\s+\((\d+)\s+tools?\)")
#: agent-pipeline-guide per-module tool counts. The live guide writes
#: "**OPP MCP (7 tools):**" — the optional ":" after ")" is the T-11 blind
#: spot this regex now covers.
_GUIDE_MODULE_RE = re.compile(r"\*\*(OPP|OL|ORF) MCP\s+\((\d+)\s+tools?\):?\*\*")
#: agent-pipeline-guide "Server Overview" table rows ("| OPP MCP | 7 | ...").
_GUIDE_TABLE_RE = re.compile(r"\|\s*(OPP|OL|ORF) MCP\s*\|\s*(\d+)\s*\|")
#: API_STABILITY §2.2 prose ("**OPP** is on its 0.6.x line. ... the 7 MCP
#: tools"). The count can sit past a sentence boundary, so the gap is
#: line-bounded (not period-bounded) and capped at 60 chars.
_API_MODULE_PROSE_RE = re.compile(r"(OPP|OL|ORF)[^\n]{0,60}?(\d+) MCP tools")
#: "7 + 21 + 6 = 34 tools" / "9+21+7=37 工具" / "= 37 module tools" /
#: "= 37 个模块工具" module-sum forms (OPP+OL+ORF). Qualifier words between
#: the total and the tool noun ("module", "个模块") are allowed.
_MODULE_SUM_RE = re.compile(
    r"(\d+)\s*\+\s*(\d+)\s*\+\s*(\d+)\s*=\s*(\d+)"
    r"(?:\s+\w+)*(?:\s*(?:tools?|工具))"
)
#: docs/PRD.md "OPP (7 tools), OL (21 tools), ORF (6 tools)" list form.
_PRD_LIST_RE = re.compile(r"(OPP|OL|ORF)\s*\((\d+)\s+tools?\)")
#: Per-repo README "MCP Surface Mastery (7 MCP tools)" counts.
_README_MCP_RE = re.compile(r"\((\d+)\s+MCP tools\)")
#: ARCHITECTURE diagram server rows ("opp-mcp-server<br/>7 tools").
_ARCH_DIAGRAM_RE = re.compile(r"(opp-mcp-server|ol-mcp|orf-mcp-server)\s*<br/?>\s*(\d+)\s+tools?")
#: ARCHITECTURE "Total: 21 tools".
_ARCH_TOTAL_RE = re.compile(r"Total:\s*(\d+)\s+tools")
#: "7 + 8 + 6 = 21 tools" in API_STABILITY / ARCHITECTURE.
_SEVEN_EIGHT_SIX_RE = re.compile(r"7\s*\+\s*8\s*\+\s*6\s*=\s*(\d+)\s+tools?")
#: "(N tools total: ...)" in SECURITY_AUDIT.
_TOTAL_PAREN_RE = re.compile(r"\((\d+)\s+tools?\s+total")
#: Per-module AGENTS.md "MCP tools (N total)".
_MODULE_AGENTS_ANY_RE = re.compile(r"MCP tools\s*\((\d+)\s+total\)")
#: ARCHITECTURE source tree rows: "mcp/server.py ← MCP server (N tools)".
_TREE_SERVER_RE = re.compile(r"MCP server\s*\((\d+)\s+tools?\)")
#: ARCHITECTURE source tree row for OL: "src/ol_mcp/ ← MCP server (N tools)".
_TREE_OL_RE = re.compile(r"src/ol_mcp/.*MCP server\s*\((\d+)\s+tools?\)")

# --- Module-doc claim shapes (issue #10) -----------------------------------
# These scan ``Omni_*/docs/**/*.md`` (and the module READMEs for the two
# prose shapes). Module attribution is DERIVED from the enclosing module
# directory, never hardcoded per file, so one regex serves all three modules.
#: OL docs/API.md "The server registers N tools".
_MODULE_DOC_REGISTERS_RE = re.compile(r"registers\s+(\d+)\s+tools?\b")
#: OL docs/ARCHITECTURE.md "N tools, all in `TOOL_REGISTRY`".
_MODULE_DOC_ALL_IN_REGISTRY_RE = re.compile(r"(\d+)\s+tools?,?\s+all in\s+`?TOOL_REGISTRY`?")
#: OPP docs/API.md "All N tool functions".
_MODULE_DOC_ALL_TOOL_FUNCTIONS_RE = re.compile(r"All\s+(\d+)\s+tool functions\b")
#: ORF docs/ARCHITECTURE.md source-tree fence "MCP server (N tools)".
_MODULE_DOC_MCP_SERVER_RE = re.compile(r"MCP server\s*\((\d+)\s+tools?\)")
#: Module README prose "exposing N tools".
_MODULE_README_EXPOSING_RE = re.compile(r"exposing\s+(\d+)\s+tools?\b")
#: Module README source-tree fence "server.py ... N tools".
_MODULE_README_SERVER_TREE_RE = re.compile(r"server\.py[^\n]*?(\d+)\s+tools?\b")
#: Module-doc self-declared version match: "vX.Y.Z (matches `pyproject.toml`)".
_MODULE_DOC_VERSION_MATCH_RE = re.compile(r"v(\d+\.\d+\.\d+)\s*\(matches\s+`?pyproject\.toml`?\)")

#: Module directory -> module key, in report order (OPP, OL, ORF).
_MODULE_DOC_DIRS: tuple[tuple[str, str], ...] = (
    ("Omni_Pre_Processor", "opp"),
    ("Omni_Localizer", "ol"),
    ("Omni_Re_Formatter", "orf"),
)


def _fail(failures: list[str], rel: str, module: str, claimed: int, expected: int) -> None:
    if claimed != expected:
        failures.append(f"{rel} claims {module} {claimed} tools, source truth is {expected}")


def _check_module_sum(failures: list[str], rel: str, text: str, source: dict[str, int]) -> None:
    total = source["opp"] + source["ol"] + source["orf"]
    for m in _MODULE_SUM_RE.finditer(text):
        opp_c, ol_c, orf_c, total_c = (int(g) for g in m.groups())
        _fail(failures, rel, "opp", opp_c, source["opp"])
        _fail(failures, rel, "ol", ol_c, source["ol"])
        _fail(failures, rel, "orf", orf_c, source["orf"])
        _fail(failures, rel, "total", total_c, total)


def check_claim_sites(root: Path, source: dict[str, int], failures: list[str]) -> None:
    """Verify every tool-count claim in the drift-prone docs matches source truth."""
    total = source["opp"] + source["ol"] + source["orf"]

    # Suite README.md + AGENTS.md: "### OPP MCP Server (9 tools)".
    for rel in ("README.md", "AGENTS.md"):
        path = root / rel
        if not path.exists():
            continue
        for m in _SUITE_HEADER_RE.finditer(read_text(path)):
            _fail(failures, rel, m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])

    # CLAUDE.md: "### opp-mcp-server (7 tools)".
    path = root / "CLAUDE.md"
    if path.exists():
        for m in _CLAUDE_SERVER_RE.finditer(read_text(path)):
            mod = SERVER_MODULE[m.group(1)]
            _fail(failures, "CLAUDE.md", mod, int(m.group(2)), source[mod])

    # docs/agent-pipeline-guide.md: "**OPP MCP (7 tools):**" + "all 34 tools
    # across" + the Server Overview table.
    path = root / "docs" / "agent-pipeline-guide.md"
    if path.exists():
        text = read_text(path)
        for m in _GUIDE_MODULE_RE.finditer(text):
            _fail(failures, "docs/agent-pipeline-guide.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])
        for m in _GUIDE_TABLE_RE.finditer(text):
            _fail(failures, "docs/agent-pipeline-guide.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])
        m = re.search(r"all\s+(\d+)\s+tools\s+across", text)
        if m:
            _fail(failures, "docs/agent-pipeline-guide.md", "total", int(m.group(1)), total)

    # docs/ARCHITECTURE.md: diagram rows, Total line, 7+8+6 line, source tree.
    path = root / "docs" / "ARCHITECTURE.md"
    if path.exists():
        text = read_text(path)
        for m in _ARCH_DIAGRAM_RE.finditer(text):
            mod = SERVER_MODULE[m.group(1)]
            _fail(failures, "docs/ARCHITECTURE.md", mod, int(m.group(2)), source[mod])
        for m in _ARCH_TOTAL_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "total", int(m.group(1)), total)
        for m in _SEVEN_EIGHT_SIX_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "total", int(m.group(1)), total)
        lines = text.splitlines()
        for i, ln in enumerate(lines):
            if "mcp/server.py" in ln and _TREE_SERVER_RE.search(ln):
                claimed = int(_TREE_SERVER_RE.search(ln).group(1))
                ctx = "\n".join(lines[max(0, i - 1):i + 3])
                mod = "opp" if "0.9" in ctx else "orf"
                _fail(failures, "docs/ARCHITECTURE.md", mod, claimed, source[mod])
        for m in _TREE_OL_RE.finditer(text):
            _fail(failures, "docs/ARCHITECTURE.md", "ol", int(m.group(1)), source["ol"])

    # docs/API_STABILITY.md: "7 + 8 + 6 = 21 tools" + named "OPP public CLI and
    # 7 MCP tools" + §2.2 prose ("... the 7 MCP tools") + the 9+21+7=37 sum.
    path = root / "docs" / "API_STABILITY.md"
    if path.exists():
        text = read_text(path)
        for m in _SEVEN_EIGHT_SIX_RE.finditer(text):
            _fail(failures, "docs/API_STABILITY.md", "total", int(m.group(1)), total)
        for m in re.finditer(r"(OPP|OL|ORF) public CLI and (\d+) MCP tools", text):
            _fail(failures, "docs/API_STABILITY.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])
        for m in _API_MODULE_PROSE_RE.finditer(text):
            _fail(failures, "docs/API_STABILITY.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])
        _check_module_sum(failures, "docs/API_STABILITY.md", text, source)

    # docs/SECURITY_AUDIT.md: "(21 tools total: 7 OPP + 8 OL + 6 ORF)".
    path = root / "docs" / "SECURITY_AUDIT.md"
    if path.exists():
        for m in _TOTAL_PAREN_RE.finditer(read_text(path)):
            _fail(failures, "docs/SECURITY_AUDIT.md", "total", int(m.group(1)), total)

    # Per-module AGENTS.md: "## MCP tools (N total)".
    for rel, mod in (
        ("Omni_Pre_Processor/AGENTS.md", "opp"),
        ("Omni_Localizer/AGENTS.md", "ol"),
        ("Omni_Re_Formatter/AGENTS.md", "orf"),
    ):
        path = root / rel
        if not path.exists():
            continue
        for m in _MODULE_AGENTS_ANY_RE.finditer(read_text(path)):
            _fail(failures, rel, mod, int(m.group(1)), source[mod])

    # Per-repo README.md: "MCP Surface Mastery (N MCP tools)".
    for rel, mod in (
        ("Omni_Pre_Processor/README.md", "opp"),
        ("Omni_Localizer/README.md", "ol"),
        ("Omni_Re_Formatter/README.md", "orf"),
    ):
        path = root / rel
        if not path.exists():
            continue
        for m in _README_MCP_RE.finditer(read_text(path)):
            _fail(failures, rel, mod, int(m.group(1)), source[mod])

    # docs/PRD.md: "OPP (7 tools), OL (21 tools), ORF (6 tools)".
    path = root / "docs" / "PRD.md"
    if path.exists():
        for m in _PRD_LIST_RE.finditer(read_text(path)):
            _fail(failures, "docs/PRD.md", m.group(1).lower(), int(m.group(2)), source[m.group(1).lower()])

    # docs/SUITE_EXPECTATIONS.md: "7 + 21 + 6 = 34 tools" sum form.
    path = root / "docs" / "SUITE_EXPECTATIONS.md"
    if path.exists():
        _check_module_sum(failures, "docs/SUITE_EXPECTATIONS.md", read_text(path), source)

    # reports/SELF_DRIVEN_LOOP_V2_REPORT.md: "opp-mcp-server (7 tools) | ol-mcp (8 tools) | ...".
    path = root / "reports" / "SELF_DRIVEN_LOOP_V2_REPORT.md"
    if path.exists():
        text = read_text(path)
        m = re.search(
            r"opp-mcp-server\s*\((\d+)\s+tools?\).*?ol-mcp\s*\((\d+)\s+tools?\).*?orf-mcp-server\s*\((\d+)\s+tools?\)",
            text,
        )
        if m:
            opp_c, ol_c, orf_c = (int(g) for g in m.groups())
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "opp", opp_c, source["opp"])
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "ol", ol_c, source["ol"])
            _fail(failures, "reports/SELF_DRIVEN_LOOP_V2_REPORT.md", "orf", orf_c, source["orf"])

    # omni-docmap SKILL.md: "all 34 tools across ... (OPP 7 / OL 21 / ORF 6)".
    path = root / ".opencode" / "skills" / "omni-docmap" / "SKILL.md"
    if path.exists():
        text = read_text(path)
        m = re.search(r"all\s+(\d+)\s+tools\s+across", text)
        if m:
            _fail(failures, "omni-docmap SKILL.md", "total", int(m.group(1)), total)
        m = re.search(r"OPP\s+(\d+)\s*/\s*OL\s+(\d+)\s*/\s*ORF\s+(\d+)", text)
        if m:
            opp_c, ol_c, orf_c = (int(g) for g in m.groups())
            _fail(failures, "omni-docmap SKILL.md", "opp", opp_c, source["opp"])
            _fail(failures, "omni-docmap SKILL.md", "ol", ol_c, source["ol"])
            _fail(failures, "omni-docmap SKILL.md", "orf", orf_c, source["orf"])


#: Module-doc tool-count shapes applied to every ``<module>/docs/**/*.md``.
_MODULE_DOC_TOOL_PATTERNS: tuple[re.Pattern[str], ...] = (
    _MODULE_DOC_REGISTERS_RE,
    _MODULE_DOC_ALL_IN_REGISTRY_RE,
    _MODULE_DOC_ALL_TOOL_FUNCTIONS_RE,
    _MODULE_DOC_MCP_SERVER_RE,
)
#: Module README prose shapes.
_MODULE_README_TOOL_PATTERNS: tuple[re.Pattern[str], ...] = (
    _MODULE_README_EXPOSING_RE,
    _MODULE_README_SERVER_TREE_RE,
)


def _module_pyproject_version(root: Path, module_dir: str) -> str | None:
    """Return ``version`` from ``<module_dir>/pyproject.toml`` (or None)."""
    pyproject = root / module_dir / "pyproject.toml"
    if not pyproject.exists():
        return None
    m = re.search(r'^version\s*=\s*"([^"]+)"', read_text(pyproject), re.MULTILINE)
    return m.group(1) if m else None


def check_module_docs(root: Path, source: dict[str, int], failures: list[str]) -> None:
    """Module-doc claim sites (issue #10): tool counts + self-declared version.

    Scans ``Omni_*/docs/**/*.md`` for the four tool-count shapes and each module
    README for the two prose shapes. The module (opp/ol/orf) is derived from the
    enclosing directory, so a stale count anywhere under a module doc tree maps
    to the right source-truth counter. Also validates the narrow
    ``vX.Y.Z ... (matches `pyproject.toml`)`` self-declared version claim against
    that module's ``pyproject.toml`` (only that form; ordinary version mentions
    are not policed). Missing module docs / pyproject files are skipped.
    """
    for module_dir, mod in _MODULE_DOC_DIRS:
        version = _module_pyproject_version(root, module_dir)
        docs = root / module_dir / "docs"
        if docs.is_dir():
            for path in sorted(docs.rglob("*.md")):
                rel = path.relative_to(root).as_posix()
                text = read_text(path)
                for pattern in _MODULE_DOC_TOOL_PATTERNS:
                    for m in pattern.finditer(text):
                        _fail(failures, rel, mod, int(m.group(1)), source[mod])
                if version is not None:
                    for m in _MODULE_DOC_VERSION_MATCH_RE.finditer(text):
                        if m.group(1) != version:
                            failures.append(
                                f"{rel} claims version v{m.group(1)} "
                                f"(matches pyproject.toml), actual is {version}"
                            )
        readme = root / module_dir / "README.md"
        if readme.exists():
            rel = readme.relative_to(root).as_posix()
            text = read_text(readme)
            for pattern in _MODULE_README_TOOL_PATTERNS:
                for m in pattern.finditer(text):
                    _fail(failures, rel, mod, int(m.group(1)), source[mod])


# ---------------------------------------------------------------------------
# --check: other gates
# ---------------------------------------------------------------------------


#: Scenario-count claim forms validated against the DERIVED library numbers
#: (total, tier-1, tier-2, tier-3). The expected count is never hardcoded —
#: the ``scenarios/**/*.yaml`` glob is the source of truth, and these docs
#: must state what the library actually contains. Each entry is
#: ``(pattern, rel-path, group-idx -> expected-slot)``; group 1..N map to
#: slots (0=total, 1=tier-1, 2=tier-2, 3=tier-3).
_SCENARIO_CLAIM_SITES: tuple[tuple[re.Pattern[str], str, tuple[int, ...]], ...] = (
    (
        re.compile(r"(\d+)-scenario library"),
        ".opencode/skills/omni-validation/SKILL.md",
        (0,),
    ),
    (
        re.compile(
            r"scenario library \*\*(\d+)\*\* = \*\*(\d+) tier-1 / (\d+) tier-2 / (\d+) tier-3\*\*"
        ),
        ".opencode/skills/omni-docmap/SKILL.md",
        (0, 1, 2, 3),
    ),
    (
        re.compile(r"scenarios/: (\d+) yaml files; tiers=\{'1': (\d+), '2': (\d+), '3': (\d+)\}"),
        ".opencode/skills/omni-docmap/SKILL.md",
        (0, 1, 2, 3),
    ),
)


def _check_scenario_claim_sites(
    root: Path, total: int, tiers: dict[str, int], failures: list[str]
) -> None:
    """Validate docs that state a scenario count / tier split against the
    derived library numbers (total + tiers['1'/'2'/'3']). Skipped when the
    claim-site doc is absent (e.g. a test fixture tree)."""
    derived = (total, tiers.get("1", 0), tiers.get("2", 0), tiers.get("3", 0))
    for pattern, rel, idxs in _SCENARIO_CLAIM_SITES:
        path = root / rel
        if not path.exists():
            continue
        for m in pattern.finditer(read_text(path)):
            claimed = tuple(int(m.group(i + 1)) for i in idxs)
            expected = tuple(derived[i] for i in idxs)
            if claimed != expected:
                failures.append(
                    f"{rel}: scenario claim {m.group(0)!r} does not match the "
                    f"derived library ({total} yaml files, "
                    f"tiers={dict(sorted(tiers.items()))}) — update the doc "
                    f"when the scenario library changes"
                )


def check_scenarios(root: Path, failures: list[str]) -> None:
    """Scenario count DERIVED from the ``scenarios/**/*.yaml`` glob (never a
    pinned number); claim-site docs stating a count/tier-split must match it.
    Input formats >= 13; '13+' claims.

    Skipped (report-only, not a failure) when ``scenarios/`` is absent. The
    library glob is the source of truth — a legitimate scenario addition or
    removal never fails the gate by itself; only a doc claiming a stale count
    does (update the claim-site docs when the library changes).
    """
    scenarios = root / "scenarios"
    if not scenarios.is_dir():
        print("  scenarios/: absent -> skip (report-only, not a failure)")
        return
    yamls = sorted(p for p in scenarios.rglob("*.yaml") if p.is_file())
    total = len(yamls)
    tiers: dict[str, int] = {}
    for p in yamls:
        tier = "1"  # missing tier field defaults to tier 1 (plan: 82/3/1)
        for line in read_text(p).splitlines():
            if re.match(r"tier\s*:", line.strip()):
                tier = line.split(":", 1)[1].strip()
                break
        tiers[tier] = tiers.get(tier, 0) + 1
    print(f"  scenarios/: {total} yaml files; tiers={dict(sorted(tiers.items()))}")
    _check_scenario_claim_sites(root, total, tiers, failures)

    opp_dir = scenarios / "opp"
    if opp_dir.is_dir():
        opp_count = len([p for p in opp_dir.glob("*.yaml") if p.is_file()])
        print(f"  scenarios/opp: {opp_count} input-format scenarios")
        if opp_count < 13:
            failures.append(f"scenarios/opp: {opp_count} input formats, expected >= 13")
        for rel in ("AGENTS.md", "README.md"):
            path = root / rel
            if path.exists() and "13+" not in read_text(path):
                failures.append(f"{rel} must claim '13+' input formats")


def check_test_matrix(root: Path, failures: list[str]) -> None:
    """Canonical test-matrix (131/64/0) + nightly (14) claims; skip absent files."""
    proj = root / "PROJECT_STATUS.md"
    if proj.exists():
        text = read_text(proj)
        if "131 PASS, 64 SKIP, 0 FAIL" not in text:
            failures.append("PROJECT_STATUS.md must carry the canonical '131 PASS, 64 SKIP, 0 FAIL'")
        for m in re.finditer(r"(\d+)\s+PASS\b", text):
            if m.group(1) != "131":
                failures.append(f"PROJECT_STATUS.md claims {m.group(1)} PASS, canonical is 131")
    else:
        print("  PROJECT_STATUS.md: absent -> skip (report-only)")
    for rel in ("TESTS.md", "ACCEPTED_GAPS.md", "docs/SECURITY_AUDIT.md"):
        path = root / rel
        if not path.exists():
            continue
        for m in re.finditer(r"(\d+)\s+PASS\b", read_text(path)):
            if m.group(1) not in ("131", "0"):
                failures.append(f"{rel} claims {m.group(1)} PASS outside the canonical matrix")
    tes = root / "TESTS.md"
    if tes.exists() and "14 nightly tests" not in read_text(tes):
        failures.append("TESTS.md must carry '14 nightly tests'")
    ulw = root / "reports" / "ulw-loop-design.md"
    if ulw.exists():
        if "(--collect-only; canonical: 14)" not in read_text(ulw):
            failures.append("reports/ulw-loop-design.md must carry '(--collect-only; canonical: 14)'")


def check_version_sync(root: Path, failures: list[str]) -> None:
    """Delegate version-doc sync to scripts/sync_version_docs.py --check."""
    sync = root / "scripts" / "sync_version_docs.py"
    if not sync.exists():
        print("  scripts/sync_version_docs.py: absent -> warn-skip")
        return
    try:
        proc = subprocess.run(
            ["python3", str(sync), "--check"],
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=120,
        )
    except (subprocess.SubprocessError, OSError) as exc:
        failures.append(f"scripts/sync_version_docs.py --check could not run: {exc}")
        return
    if proc.returncode != 0:
        failures.append(
            f"scripts/sync_version_docs.py --check failed (rc={proc.returncode}): "
            f"{(proc.stdout or proc.stderr).strip()}"
        )


def check_stray(root: Path, failures: list[str]) -> None:
    """No tests/test_bug_*.py files may live in the shipped tree."""
    tests = root / "tests"
    if not tests.is_dir():
        print("  tests/: absent -> skip")
        return
    stray = sorted(tests.glob("test_bug_*"))
    if stray:
        names = ", ".join(p.name for p in stray)
        print(f"  Stray test_bug_* files: {names} -> FAIL")
        failures.append(f"tests/ contains {len(stray)} test_bug_* file(s): {names}")
    else:
        print("  Stray test_bug_* files in tests/: none -> ok")


def check_inventory(root: Path, failures: list[str]) -> None:
    """docs/dev/doc-inventory.md must exist and carry the AUTO-GENERATED header."""
    out = root / "docs" / "dev" / "doc-inventory.md"
    if not out.exists():
        print("  docs/dev/doc-inventory.md: missing -> FAIL")
        failures.append("docs/dev/doc-inventory.md missing — run python3 scripts/doc_inventory.py first")
        return
    text = read_text(out)
    first = text.splitlines()[0] if text.splitlines() else ""
    if first.startswith("<!-- AUTO-GENERATED by scripts/doc_inventory.py"):
        print("  docs/dev/doc-inventory.md: AUTO-GENERATED header present -> ok")
    else:
        print("  docs/dev/doc-inventory.md: AUTO-GENERATED header MISSING -> FAIL")
        failures.append(
            "docs/dev/doc-inventory.md is stale: missing its AUTO-GENERATED header — "
            "regenerate with python3 scripts/doc_inventory.py"
        )


#: Status-marker convention for archived docs (first content line).
ARCHIVED_MARKER_RE = re.compile(r"^>\s*\*\*Status:\s*ARCHIVED\b")

#: Maintained (non-archive) Markdown files scanned by the referential gate.
#: Root instruction files + authoritative docs — the surfaces an agent actually
#: follows. ``docs/archive/`` is excluded by design: archived docs may
#: legitimately reference long-gone paths.
REFERENTIAL_SCOPE = (
    "AGENTS.md",
    "README.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    "TESTS.md",
    "SETUP.md",
    "CONTEXT.md",
    "CONTRACT.md",
    "ACCEPTED_GAPS.md",
    "PRODUCTION_READINESS.md",
    "PROJECT_STATUS.md",
    "COMPATIBILITY.md",
    "docs/ARCHITECTURE.md",
    "docs/API_STABILITY.md",
    "docs/SECURITY.md",
    "docs/PRD.md",
    "docs/agent-pipeline-guide.md",
    "docs/ERROR_CODES.md",
    ".opencode/skills/omni-docmap/SKILL.md",
)

#: Backticked paths inside instruction files; ``:NN`` line refs are stripped.
_PATH_TOKEN_RE = re.compile(r"`([^`\n]+)`")
_LINE_REF_RE = re.compile(r":\d+(?:-\d+)?$")
_LINK_TARGET_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)")

#: Tokens that are intentional historical references (deleted files mentioned
#: in security/incident narratives) or gitignored runtime config that
#: legitimately does not exist in the tree.
_HISTORICAL_PATH_TOKENS = {
    "Omni_Localizer/config/book_localization.yaml",
    "config/book_localization.yaml",
    "config/secret.yaml",
    "config/production.yaml",
    "config/local.yaml",
    "config/local*.yaml",
    "scripts/mcp_bridge.py",
    ".cursor/mcp.json",
}

#: Link targets that are markdown-syntax illustrations ("![alt](path)"),
#: not real files.
_SYNTAX_EXAMPLE_TARGETS = {"path", "image_001.png"}

#: Skip tokens that are not real repo paths (globs, templates, URLs, anchors,
#: env vars, virtualenv internals, generated/dist artifacts).
_SKIP_TOKEN_SUBSTR = (
    "{",
    "}",
    "[",
    "]",
    "<",
    ">",
    "*",
    "http://",
    "https://",
    "#",
    "://",
    "$",
    ".venv",
    "dist/",
    "__pycache__",
    ".git/",
    "word/",
    "references/",
    "~",
)

#: Root-level files with no dot in the name that are still real paths.
_ROOT_FILE_ALLOW = {"Makefile", "VERSION", "LICENSE", "Dockerfile"}

#: Module roots tried as fallback resolution domains for source paths that
#: are written relative to a sub-repo (e.g. ``opp/mcp/_errors.py``).
_MODULE_ROOTS = (
    "Omni_Pre_Processor",
    "Omni_Localizer",
    "Omni_Re_Formatter",
)
#: Suffix under a module root where source paths live (``<module>/src``).
_MODULE_SRC = "src"
#: Sub-package prefixes under ``<module>/src`` for per-module source paths
#: (``mcp/config.py`` lives at ``src/opp/mcp/config.py``).
_MODULE_PKGS = ("opp", "ol", "orf", "ol_mcp")


def _is_path_token(token: str) -> bool:
    """A backticked token looks like a repo path iff it resolves to a file-ish
    name: a slash-separated path whose basename has an extension, a dotfile or
    root file with an extension, or an allowlisted root file. This excludes
    CLI flags (``--check``), code identifiers (``CLI_ERROR``), branch
    prefixes (``feat/``), bare extensions (``.md``), artifact names
    (``skeleton.zip``) and bare directory names (``scenarios/``)."""
    if token in _ROOT_FILE_ALLOW:
        return True
    if any(ch in token for ch in " \t=()|;&"):
        return False
    # Elided/redacted tokens ("bce-v3/ALTpa...") are not paths.
    if "..." in token:
        return False
    # "path.py:SYMBOL" is a symbol reference, not a path with a line number.
    if ":" in token:
        _, _, suffix = token.partition(":")
        if not suffix.isdigit():
            return False
    if "/" not in token:
        # No separator: only resolve-able root files (".gitignore", ".env").
        # Bare ".ext" / "name.ext" / artifact names are not paths.
        return False
    base = token.rsplit("/", 1)[-1]
    return "." in base


def _resolve_token(root: Path, token: str) -> Path | None:
    """Resolve a path token: repo-root first, then each module root
    (``<module>/`` and ``<module>/src/<pkg>/``)."""
    for base in (root, *(root / m for m in _MODULE_ROOTS)):
        for prefix in ("", _MODULE_SRC, *(f"{_MODULE_SRC}/{p}" for p in _MODULE_PKGS)):
            candidate = (base / prefix / token).resolve()
            if candidate.exists():
                return candidate
    return None


def _is_maintained_md(root: Path, rel: str) -> bool:
    path = root / rel
    return path.is_file() and "docs/archive" not in path.as_posix()


def check_archive(root: Path, failures: list[str]) -> None:
    """Gate A — archive discipline.

    * Every ``docs/archive/*.md`` file must carry an ``ARCHIVED`` status marker
      as its first content line.
    * No maintained (non-archive) doc under ``docs/`` may carry an
      ``ARCHIVED`` status marker in its first 3 lines.
    """
    archive_dir = root / "docs" / "archive"
    if archive_dir.is_dir():
        for path in sorted(archive_dir.glob("*.md")):
            if path.name == "README.md":
                # The archive index README documents the marker convention; it
                # is not itself a retired doc, so it carries no ARCHIVED marker.
                continue
            lines = read_text(path).splitlines()
            first = lines[0] if lines else ""
            if not ARCHIVED_MARKER_RE.search(first):
                failures.append(
                    f"{path.relative_to(root)}: archived doc missing "
                    f"'Status: ARCHIVED' first-line marker"
                )
    docs = root / "docs"
    if docs.is_dir():
        for path in sorted(docs.rglob("*.md")):
            if "archive" in path.relative_to(docs).parts:
                continue
            head = "\n".join(read_text(path).splitlines()[:3])
            if ARCHIVED_MARKER_RE.search(head):
                failures.append(
                    f"{path.relative_to(root)}: carries an ARCHIVED status marker "
                    f"outside docs/archive/ — move it or remove the marker"
                )


def _strip_line_ref(token: str) -> str:
    """Strip a trailing ``:NN``/``:NN-NN`` line reference from a path token."""
    return _LINE_REF_RE.sub("", token).strip()


def check_referential(root: Path, failures: list[str]) -> None:
    """Gate B — referential integrity (the context-rot gate).

    For every maintained instruction doc: (1) every relative Markdown link
    target resolves to an existing file or directory; (2) every backticked
    repo-path token resolves relative to the repo root. Anchors, URLs, globs,
    templates, env vars, and virtualenv internals are skipped.
    """
    for rel in REFERENTIAL_SCOPE:
        path = root / rel
        if not path.exists():
            continue
        text = read_text(path)

        # (1) Markdown link targets: `[label](target)`.
        for m in _LINK_TARGET_RE.finditer(text):
            target = m.group(1).strip()
            if not target or any(s in target for s in _SKIP_TOKEN_SUBSTR):
                continue
            # Fragment-only ("#sec") links are intra-file — always fine.
            if target.startswith("#"):
                continue
            # Rooted paths ("/foo") — not repo-relative Markdown links.
            if target.startswith("/"):
                continue
            if target in _SYNTAX_EXAMPLE_TARGETS:
                continue
            target = _strip_line_ref(target)
            if not target:
                continue
            resolved = (path.parent / target).resolve()
            if not resolved.exists():
                failures.append(f"{rel}: broken link -> {target}")

        # (2) Backticked repo-path tokens (only path-shaped tokens, see
        # _is_path_token: excludes CLI flags, code identifiers, branch names).
        for m in _PATH_TOKEN_RE.finditer(text):
            token = m.group(1).strip()
            if not token or any(s in token for s in _SKIP_TOKEN_SUBSTR):
                continue
            token = _strip_line_ref(token)
            if not token:
                continue
            # Method calls ("PathValidator.validate_path()") are code, not paths.
            if "()" in token:
                continue
            if not _is_path_token(token):
                continue
            if token in _HISTORICAL_PATH_TOKENS:
                continue
            if _resolve_token(root, token) is None:
                failures.append(f"{rel}: dead path token -> `{token}`")


def check_line_claims(root: Path, failures: list[str]) -> None:
    """Gate C — skill line-count claims vs actual (skill sync, ±15%).

    ``omni-docmap/SKILL.md`` tables carry ``~N`` line-count claims per file;
    verify each against the real file when it exists.
    """
    skill = root / ".opencode" / "skills" / "omni-docmap" / "SKILL.md"
    if not skill.exists():
        return
    for m in re.finditer(r"\|\s*`([^`]+)`\s*\|\s*~?(\d+)\s*\|", read_text(skill)):
        rel, claimed = m.group(1), int(m.group(2))
        if rel.startswith((".", "..", "/")) or rel.startswith("http"):
            continue
        path = root / rel
        if not path.exists():
            continue  # existence handled by Gate B
        actual = len(read_text(path).splitlines())
        lo, hi = int(claimed * 0.85), int(claimed * 1.15)
        if not (lo <= actual <= hi):
            failures.append(
                f"omni-docmap SKILL.md claims `{rel}` ~{claimed} lines, "
                f"actual is {actual} (±15% band {lo}-{hi})"
            )


def run_check(root: Path) -> list[str]:
    """Run all --check gates; return the list of human-readable failures."""
    failures: list[str] = []
    print("doc_inventory --check")

    # 1. Source truth (computed from the MCP source files, never hardcoded).
    source: dict[str, int] = {}
    src_paths = {
        "opp": root / "Omni_Pre_Processor" / "src" / "opp" / "mcp" / "server.py",
        "ol": root / "Omni_Localizer" / "src" / "ol_mcp" / "tools.py",
        "orf": root / "Omni_Re_Formatter" / "src" / "orf" / "mcp" / "server.py",
    }
    counters = {
        "opp": count_tool_schemas,
        "ol": count_tool_registry,
        "orf": count_listed_tools,
    }
    for key, path in src_paths.items():
        if path.exists():
            source[key] = counters[key](path)
        else:
            source[key] = 0
            print(f"  source {key}: {path.relative_to(root)} missing -> 0")
    total = source["opp"] + source["ol"] + source["orf"]
    print(f"SOURCE: OPP={source['opp']} OL={source['ol']} ORF={source['orf']} total={total}")

    # 2. Claim sites vs source truth.
    check_claim_sites(root, source, failures)

    # 2b. Module-doc claim sites (tool counts + self-declared version, issue #10).
    check_module_docs(root, source, failures)

    # 3. Scenario count + input formats (skipped when scenarios/ absent).
    check_scenarios(root, failures)

    # 6. Test matrix + nightly claims.
    check_test_matrix(root, failures)

    # 7. Version sync (delegate).
    check_version_sync(root, failures)

    # 8. Stray test_bug_* files.
    check_stray(root, failures)

    # 9. Inventory freshness.
    check_inventory(root, failures)

    # 10. Archive discipline (docs/archive/ markers).
    check_archive(root, failures)

    # 11. Referential integrity (links + repo-path tokens in instruction docs).
    check_referential(root, failures)

    # 12. Skill line-count claims vs actual (omni-docmap SKILL.md).
    check_line_claims(root, failures)

    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Omni Suite documentation inventory + run the "
        "source-truth --check (docs/dev/doc-inventory.md)."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify source-truth tool counts vs claim sites, scenario/test-matrix "
        "claims, version-sync delegation, stray test_bug_* files, and inventory "
        "freshness. No files are written. Exits 1 on any failure.",
    )
    parser.add_argument(
        "--root",
        default=str(ROOT),
        help="Rebase every relative path onto DIR (default: repo root).",
    )
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.check:
        failures = run_check(root)
        print()
        if failures:
            print(f"check FAILED ({len(failures)} issue(s)):")
            for f in failures:
                print(f"  - {f}")
            return 1
        print("check passed: source truth matches claims, no stray files, inventory fresh.")
        return 0

    docs = root / "docs"
    out = docs / "dev" / "doc-inventory.md"
    rows = scan_docs(docs, out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_report(rows), encoding="utf-8")
    total_lines = sum(r["lines"] for r in rows)
    print(f"Wrote {out} ({len(rows)} files, {total_lines} lines).")
    print("Regenerate after doc changes; verify with --check (exit 0 = clean).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
